// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/popupai.proto

package popupai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "explain", "define", etc.
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeReq) Reset() {
	*x = AnalyzeReq{}
	mi := &file_proto_popupai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeReq) ProtoMessage() {}

func (x *AnalyzeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_popupai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeReq.ProtoReflect.Descriptor instead.
func (*AnalyzeReq) Descriptor() ([]byte, []int) {
	return file_proto_popupai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AnalyzeReq) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_proto_popupai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_popupai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_popupai_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Token) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type CaretRect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaretRect) Reset() {
	*x = CaretRect{}
	mi := &file_proto_popupai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaretRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaretRect) ProtoMessage() {}

func (x *CaretRect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_popupai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaretRect.ProtoReflect.Descriptor instead.
func (*CaretRect) Descriptor() ([]byte, []int) {
	return file_proto_popupai_proto_rawDescGZIP(), []int{2}
}

func (x *CaretRect) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CaretRect) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CaretRect) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *CaretRect) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type TriggerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caret         *CaretRect             `protobuf:"bytes,1,opt,name=caret,proto3" json:"caret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerReq) Reset() {
	*x = TriggerReq{}
	mi := &file_proto_popupai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReq) ProtoMessage() {}

func (x *TriggerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_popupai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReq.ProtoReflect.Descriptor instead.
func (*TriggerReq) Descriptor() ([]byte, []int) {
	return file_proto_popupai_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerReq) GetCaret() *CaretRect {
	if x != nil {
		return x.Caret
	}
	return nil
}

var File_proto_popupai_proto protoreflect.FileDescriptor

const file_proto_popupai_proto_rawDesc = "" +
	"\n" +
	"\x13proto/popupai.proto\x12\apopupai\"P\n" +
	"\n" +
	"AnalyzeReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"5\n" +
	"\x05Token\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"C\n" +
	"\tCaretRect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x05R\x01h\"6\n" +
	"\n" +
	"TriggerReq\x12(\n" +
	"\x05caret\x18\x01 \x01(\v2\x12.popupai.CaretRectR\x05caret2m\n" +
	"\x04Core\x120\n" +
	"\aAnalyze\x12\x13.popupai.AnalyzeReq\x1a\x0e.popupai.Token0\x01\x123\n" +
	"\fTriggerPopup\x12\x13.popupai.TriggerReq\x1a\x0e.popupai.TokenBEZCgithub.com/yourusername/in-other-words/apps/daemon_go/proto;popupaib\x06proto3"

var (
	file_proto_popupai_proto_rawDescOnce sync.Once
	file_proto_popupai_proto_rawDescData []byte
)

func file_proto_popupai_proto_rawDescGZIP() []byte {
	file_proto_popupai_proto_rawDescOnce.Do(func() {
		file_proto_popupai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_popupai_proto_rawDesc), len(file_proto_popupai_proto_rawDesc)))
	})
	return file_proto_popupai_proto_rawDescData
}

var file_proto_popupai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_popupai_proto_goTypes = []any{
	(*AnalyzeReq)(nil), // 0: popupai.AnalyzeReq
	(*Token)(nil),      // 1: popupai.Token
	(*CaretRect)(nil),  // 2: popupai.CaretRect
	(*TriggerReq)(nil), // 3: popupai.TriggerReq
}
var file_proto_popupai_proto_depIdxs = []int32{
	2, // 0: popupai.TriggerReq.caret:type_name -> popupai.CaretRect
	0, // 1: popupai.Core.Analyze:input_type -> popupai.AnalyzeReq
	3, // 2: popupai.Core.TriggerPopup:input_type -> popupai.TriggerReq
	1, // 3: popupai.Core.Analyze:output_type -> popupai.Token
	1, // 4: popupai.Core.TriggerPopup:output_type -> popupai.Token
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_popupai_proto_init() }
func file_proto_popupai_proto_init() {
	if File_proto_popupai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_popupai_proto_rawDesc), len(file_proto_popupai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_popupai_proto_goTypes,
		DependencyIndexes: file_proto_popupai_proto_depIdxs,
		MessageInfos:      file_proto_popupai_proto_msgTypes,
	}.Build()
	File_proto_popupai_proto = out.File
	file_proto_popupai_proto_goTypes = nil
	file_proto_popupai_proto_depIdxs = nil
}
